# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0245e0a2e2ce6ce5c4ad41e2ac4e32c95fa2981835f184c98d9cf037b3e2fed736b1589503fbddd71f73f3e314ee9414ee071f96f6532d5d3eb0436b7e82314b

test:
  secret_key_base: f2710f6b6505b2de80cdf316cd00874069dd8ab20cd0235caa6a461d8957c9133083a7e8e1a0ebd38fa1837904c740c9631e22a5cf7c64842bb644cbd10ad171

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
